---
name: link-check
on:  # yamllint disable-line rule:truthy
  # Schedule check each day at 8 UTC
  schedule: [{cron: "0 8 * * *"}]
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  markdown-link-check:
    name: Markdown link check
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Check markdown links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          file-path: './README.md'
          config-file: './mlc_config.json'
