---
name: Lint

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run awesome-lint
        run: npx awesome-lint

      - name: yamllint
        uses: karancode/yamllint-github-action@master
